config/routes.rb
Account::Application.routes.draw do
  root "chits#index"
  resources:chits

end

app/models/chit.rb
class Chit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chits_controller.rb
class ChitsController < ApplicationController
  def index
    @chits=Chit.all
  end
  
  def new
    @chit=Chit.new
  end
  
  def create
    @chit=Chit.new(chit_params)
	if @chit.save
	 flash[:notice]="phiếu chi đã tạo"
	 redirect_to @chit
	else
	#nothing,yet
	end
  end
  
  def show
    @chit=Chit.find(params[:id])
  end
  
  def edit
    @chit = Chit.find(params[:id])
  end
  
  def update
   @chit=Chit.find(params[:id])
   @chit.update(chit_params)
   flash[:notice]="phiếu chi đã cập nhật xong"
   redirect_to @chit
  end
  
  def destroy
    @chit=Chit.find(params[:id])
	@chit.destroy
	flash[:notice]="phiếu chi đã được xóa"
	redirect_to chits_path
  end
  private
  def chit_params
    params.require(:chit).permit(:serial, :name, :address, :reason, :payment, :day, :month, :year, :ability, :dean, :tabolator, :payer, :cashier)
  end
end

app/helpers/application_helper.rb
#encoding UTF-8
module ApplicationHelper
 def title(*parts)
  unless parts.empty?
   content_for :title do
   (parts<< "PHIẾU CHI").join("-")
   end
  end
 end
end

app/helpers/chits_helper.rb
module ChitsHelper
end

app/views/chits/_form.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<%=form_for(@chit) do |f| %>
 <p>
  <%=f.label:serial, "số phiếu" %><br />
  <%=f.number_field:serial %>
 </p>
 
 <p>
  <%=f.label:name, "tên người tạo phiếu" %><br />
  <%=f.text_field:name %>
 </p>
 
 <p>
  <%=f.label:address, "địa chỉ" %><br />
  <%=f.text_field:address %>
 </p>
 
 <p>
  <%=f.label:reason, "lý do nộp" %><br />
  <%=f.text_field:reason %>
 </p>
 
 <p>
  <%=f.label:payment, "số tiền" %><br />
  <%=f.number_field:payment %>
 </p>
 
 <p>
  <%=f.label:day, "ngày" %><br />
  <%=f.number_field:day %>
 </p>
 
 <p>
  <%=f.label:month, "tháng" %><br />
  <%=f.number_field:month %>
 </p>
 
 <p>
  <%=f.label:year, "năm" %><br />
  <%=f.number_field:year %>
 </p>
 
 <p>
  <%=f.label:ability, "nguồn kinh phí" %><br />
  <%=f.text_field:ability %>
 </p>
 
 <p>
  <%=f.label:dean, "chủ nhiệm khoa" %><br />
  <%=f.text_field:dean %>
 </p>
 
 <p>
  <%=f.label:tabolator, "người lập phiếu" %><br />
  <%=f.text_field:tabolator %>
 </p>
 
 <p>
  <%=f.label:payer, "người nộp tiền" %><br />
  <%=f.text_field:payer %>
 </p>
 
 <p>
  <%=f.label:cashier, "thủ quỹ" %><br />
  <%=f.text_field:cashier %>
 </p>
 <% if @chit.new_record? %>
 
 <%=f.submit "tạo phiếu" %>
 <% else %>
 
 <%=f.submit "cập nhật phiếu chi" %>
 <% end %>
<% end %>

app/views/chits/edit.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<h2>sửa phiếu chi</h2>
<%= render "form" %>
<%=link_to 'Hiến thị phiếu chi vừa sửa', @chit %> <!--hiện lại nội dung của phiếu mình định sửa-->

app/views/chits/index.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<%=link_to "phiếu chi mới",new_chit_path %>
<!--%=link_to "Danh sách phiếu chi",chits_path %-->
<h2>Danh sách phiếu chi</h2>

<html>
<body>
<table width="1000px">
	<% @chits.each do |chit| %>
	<tr>

	    <td><%= chit.serial %></td>
		<td><li><%=link_to chit.name, chit %></li></td>
		<td><%= chit.reason %></td>
		<td><%= chit.payment %></td>
		<td><%= chit.day %></td>
		<td><%= chit.month %></td>
		<td><%= chit.year %></td>
		<td><%= chit.dean %></td>
		<td><%= chit.tabolator %></td>
		<td><%= chit.ability %></td>
		<td><%= chit.payer %></td>
		<td><%= chit.cashier %></td>
	</tr>
    <% end %>
</table>
<body>
</html>

app/views/chits/new.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<h2>phiếu chi mới</h2>
<%= render "form" %>

app/views/chits/show.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<!--<% @title= "hovaten-chit-account" %>-->
<% title(@chit.name, "Chits") %>
<h2>PHIẾU CHI MỚI</h2>
<p>Số phiếu: <%=@chit.serial %></p>
<p>Tên người tạo phiếu: <%=@chit.name %></p>
<p>Địa chỉ: <%=@chit.address %></p>
<p>Lý do nộp: <%=@chit.reason %></p>
<p>Số tiền: <%=@chit.payment %></p>
<p>Ngày: <%=@chit.day %></p>
<p>Tháng: <%=@chit.month %></p>
<p>Năm: <%=@chit.year %></p>
<p>Nguồn kinh phí: <%=@chit.ability %></p>
<p>Chủ nhiệm khoa: <%=@chit.dean %></p>
<p>Người lập phiếu: <%=@chit.tabolator %></p>
<p>Người nộp tiền: <%=@chit.payer %></p>
<p>Thủ quỹ: <%=@chit.cashier %></p>

<%=link_to "Phiếu chi mới",new_chit_path(@chit) %>  |
<%=link_to 'Quay lại danh sách phiếu chi', :action=>'index' %>  |
<%=link_to "sửa phiếu chi",edit_chit_path(@chit)  %>
<%= link_to "xóa phiếu chi", chit_path(@chit), method: :delete, data: { confirm: "Bạn có chắc muốn xóa phiếu chi này?"} %>

app/views/layouts/application.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<!DOCTYPE html>
<html>
<head>
   
 <!-- <title><%= @title || "hovaten" %></title>-->
 <title>
  <% if content_for?(:title) %>
    <%= yield(:title) %>
  <% else %>
    PHIẾU CHI
  <% end %>
 </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
    <div class='flash' id='<%= key %>'>
      <%= value %>
    </div>
<% end %>
 
<%= yield %>

</body>
</html>